services:
  gateway:
    image: readingisgood/gateway:latest
    ports:
      - "8000:8000"
    networks:
      - reading-is-good-network

  bookstore:
    image: readingisgood/bookstore:latest
    ports:
      - "8001:8001"
    networks:
      - reading-is-good-network

  orders:
    image: readingisgood/orders:latest
    ports:
      - "8002:8002"
    networks:
      - reading-is-good-network

  keycloak-mock:
    image: readingisgood/keycloack-mock:latest
    ports:
      - "5000:5000"
    networks:
      - reading-is-good-network

networks:
  reading-is-good-network: {}
